sudo: required

language: go

go:
  - 1.6

services:
  - docker

before_install:
  - docker pull quay.io/phamhongviet/serf
  - docker pull golang:1.6-alpine

install:
  - make get-deps

before_script:
  - make setup-test

script:
  - make test
  - ./publish.sh
