sudo: required

language: go

services:
  - docker

before_install:
  - docker pull quay.io/phamhongviet/serf

install:
  - go get github.com/golang/lint/golint
  - go get github.com/hashicorp/serf/client
  - go get github.com/miekg/dns

before_script:
  - make setup-test

script:
  - make test
